sonar.projectKey=dev-christianmendes_desafio-ibge-1209-lev
sonar.projectName=desafio-ibge-1209-lev
sonar.organization=dev-christianmendes
sonar.python.version=3.10
sonar.sources=src
sonar.tests=tests
sonar.sourceEncoding=UTF-8
sonar.python.coverage.reportPaths=coverage.xml
sonar.exclusions=**/fake_playwright.py,tools/**